edition = "2018"
newline_style = "Unix"
use_field_init_shorthand = true

### Additional Configs ###
# These don't work on a stable toolchain, so disabled for now.

# unstable_features = true
# blank_lines_lower_bound = 1
# error_on_line_overflow = true
# error_on_unformatted = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_macro_bodies = true
# format_strings = true
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# wrap_comments = true
