[package]
name = "block-grid"
version = "0.1.0"
authors = ["Gunvir Ranu <g1ranu@gmail.com>"]
description = "A quick, cache-conscious tiled 2D array."
edition = "2018"
license = "MIT"
publish = false

[lib]
bench = false

[workspace]
members = ["tb-suite"]
