[package]
name = "tb-suite"
version = "0.0.0"
authors = ["Gunvir Ranu <mail@gunvirranu.com>"]
description = "A test/bench suite for the `block-grid` crate."
edition = "2018"
publish = false

[dependencies]
block-grid = { path = ".." }
array2d = "0.2.1"

[dev-dependencies]
fastrand = "1.3.3"
