name: Bench PR

on: [workflow_dispatch]

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run Criterion
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --workspace
