name: Bench PR

on: [workflow_dispatch]

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Bench base
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --workspace

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Bench changes
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --workspace
