name: CI

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.*'
  schedule:
    - cron: '37 4 * * 6'
  pull_request:

jobs:

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust: [ stable, beta ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --workspace

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --workspace

      - name: Test Docs
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --workspace

      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
